# ===========================================
# PROFIL DE PRODUCTION
# ===========================================
spring:
    config:
    activate:
      on-profile: production

# Database configuration pour production
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lims_db}
    username: ${DB_USERNAME:lims_user}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false