server:
  port: 8091

spring:
  application:
    name: lims-laboratory-service
  profiles:
    active: development

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/lims_core
    username: lims_user
    password: lims_password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Security configuration (to be configured with Keycloak)
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://auth.lims.local/realms/lims-staff
        jwk-set-uri: http://auth.lims.local/realms/lims-staff/protocol/openid-connect/certs

# Logging
logging:
  level:
    com.lims.laboratory: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG